### ISSUE TITLE
issue with crafter?

### ISSUE THREAD

**Issue by grillotine** [axialeaa/DoormatCarpetExtension#10]
doing some testing and just having this mod in the folder without any rules applied will cause the server console to spam [21:53:24] [Server thread/WARN]: Activator Rail does not support quasi-connectivity modification! Returning vanilla call. when try to use any autocrafter. and it will pretty easily cause server breaking lag.

**Comment by axialeaa** [comment]
not this issue again...

are you certain it's the crafter causing the log output? can we try to narrow it down to one specific component state change?

**Comment by grillotine** [comment]
i just checked it is definitely related to the new crafter block

**Comment by grillotine** [comment]
its any time its powered which is why i think its so devastating. i was testing something with a 4gt observer clock and it only had 4 crafters and server mspt went over 50

**Comment by axialeaa** [comment]
that sure is devastating. thanks for reporting; i'll look into it after my voluntary hiatus!

**Comment by axialeaa** [comment]
ok so, i was silly

i forgot the word `else`. that's literally it. it'll be fixed soon lolol
