### ISSUE TITLE
Server log spam latest release 1.21

### ISSUE THREAD

**Issue by sternschnaube** [axialeaa/DoormatCarpetExtension#11]
[Server thread/WARN]: null does not support quasi-connectivity modification! Returning vanilla call.

If a player connects, this message comes up a hundred times 😓

**Comment by axialeaa** [comment]
this is the second bug report relating to this issue! i have some fixin to do

**Comment by axialeaa** [comment]
does this only happen on a dedicated server?

**Comment by axialeaa** [comment]
i may have already fixed it as part of #10 but i want to double check before i jump to conclusions

**Comment by venaminecraft** [comment]
> does this only happen on a dedicated server?

I don't have the mod installed on Client. 

> i may have already fixed it as part of #10 but i want to double check before i jump to conclusions

Can you pass me please the build, I would like to test if the spam still occurs 😄

**Comment by axialeaa** [comment]
i'll perhaps release a public beta version within the coming week

**Comment by venaminecraft** [comment]
Perfecto, thanks!

**Comment by axialeaa** [comment]
please check if this issue is still present in 1.3.0

**Comment by venaminecraft** [comment]
Seems to work now, thank you 😊

**Comment by axialeaa** [comment]
great stuff! i'll mark this as a duplicate of #10
