### ISSUE TITLE
this mod together ~~with tweakeroo~~ causes a client crash when opening a door or fence gate on any server

### ISSUE THREAD

**Issue by nickademas** [axialeaa/DoormatCarpetExtension#3]
[crash-2023-12-20_21.43.02-client.txt](https://github.com/axialeaa/DoormatCarpetExtension/files/13732389/crash-2023-12-20_21.43.02-client.txt)

**Comment by axialeaa** [comment]
Does this happen only when the `/updatetype` rule is modified, or is it across-the-board?

**Comment by axialeaa** [comment]
Dev note: the tweakeroo log line is just because tweakeroo keeps track of certain kinds of interactions for the sake of fast right click, fast block placement etc. features. It's actually a red herring; the crash happens without tweakeroo.

**Comment by axialeaa** [comment]
Will be fixed in 1.0.3. Thanks for reporting, and sorry for the inconvenience!
