### ISSUE TITLE
composterSideInputs crashes with lithium's mixin.alloc.composter

### ISSUE THREAD

**Issue by nickademas** [axialeaa/DoormatCarpetExtension#4]
Trying to use compostersideinputs when the lithium mod is installed results in a crash. Entering "mixin.alloc.composter false" into the lithium mod config fixes this.
[crash-2023-12-29_22.58.12-server.txt](https://github.com/axialeaa/DoormatCarpetExtension/files/13796362/crash-2023-12-29_22.58.12-server.txt)

**Comment by axialeaa** [comment]
At a first look, this bug may be unfixable due to the use of `@Overwrite` in Lithium's mixin. It will always try to replace what I've already given it, regardless of the changes I may make.
