### ISSUE TITLE
Biome Based Spawners (Suggestion)

### ISSUE THREAD

**Issue by DrKhaoticSarcasm** [axialeaa/DoormatCarpetExtension#5]
Could we generate mob spawners based on the biome variants?

Skeleton become Stray in Snowy Biomes
Zombie become Drowned in Water Biomes
Zombie become Husk in Hot Biomes
Skeleton become Bogged in Swampy Biomes?

Just a thought for renewable/unique natural dungeon generation?

**Comment by axialeaa** [comment]
this is a REALLY good idea. i'll have a look into this for the next update for sure! thank you!

**Comment by DrKhaoticSarcasm** [comment]
Awesome! I'll keep any eye out for the update!

**Comment by axialeaa** [comment]
implemented in the next update!
